// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ZnjqPpHWnLxthp1TUn4XNwDIMfoZ6Ss',
    appId: '1:1039428245850:web:a8efc7322c61b7be0e7b63',
    messagingSenderId: '1039428245850',
    projectId: 'groceries-list-70015',
    authDomain: 'groceries-list-70015.firebaseapp.com',
    storageBucket: 'groceries-list-70015.appspot.com',
    measurementId: 'G-Q1J2NQT2QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA296bzLL29jhDv1YrBq6Z5M5sakmgweNg',
    appId: '1:1039428245850:android:abe24dff5320210d0e7b63',
    messagingSenderId: '1039428245850',
    projectId: 'groceries-list-70015',
    storageBucket: 'groceries-list-70015.appspot.com',
  );

}